-- knowledge_chunks: the single table the intake pipeline writes to and the
-- live site (knowledge.thirstyc.com) reads from. Reconciled 2026-09-16 —
-- this file previously described a different, incompatible table
-- (source_file/title/category columns) that nothing actually used; the real
-- table below already existed in Supabase with source_doc/section_title/
-- chunk_type, plus a wine_id link and an embed-knowledge-on-write trigger
-- that auto-populates `embedding` via an Edge Function on insert/update.
--
-- This file is a reference snapshot, not a script to run — the table
-- already exists. New columns were added via ALTER TABLE, not recreated.

create extension if not exists vector;

create table if not exists knowledge_chunks (
  id bigint generated by default as identity primary key,
  content text not null,
  embedding vector(384),
  source_doc text not null,
  section_title text,
  chunk_type text not null default 'atlas',
  wine_id uuid,
  chunk_index int,
  summary text,
  tags text[] default '{}',
  status text not null default 'published' check (status in ('draft', 'published')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz,
  unique (source_doc, chunk_index)
);

create index if not exists knowledge_chunks_embedding_idx
  on knowledge_chunks using ivfflat (embedding vector_cosine_ops)
  with (lists = 100);

create index if not exists knowledge_chunks_status_idx
  on knowledge_chunks (status);

-- Similarity search over published chunks only. Not currently called from
-- any page — search.html does a plain ilike text filter instead (see
-- PIPELINE-GAP-AUDIT.md). Wire this up when vector search gets built.
create or replace function match_knowledge_chunks(
  query_embedding vector(384),
  match_count int default 5
)
returns table (
  id bigint,
  source_doc text,
  section_title text,
  content text,
  summary text,
  tags text[],
  chunk_type text,
  similarity float
)
language sql stable
as $$
  select
    id, source_doc, section_title, content, summary, tags, chunk_type,
    1 - (embedding <=> query_embedding) as similarity
  from knowledge_chunks
  where status = 'published'
  order by embedding <=> query_embedding
  limit match_count;
$$;
