// Single source of truth for topic-*.html pages AND for the answer-card
// routing table in supabase-client.js (TOPIC_PAGE_SLUGS, SOURCE_DOC_SLUG_
// OVERRIDES, TOPIC_KEYWORDS). Add an entry here and run
// `npm run generate:topics` instead of hand-editing either.
//
// kind determines which Supabase query shape generate-topic-pages.mjs uses:
//   - 'grape'    chunk_type=grape overview, single chunk_type=qa QA fetch
//   - 'region'   chunk_type=region overview, single chunk_type=region-qa QA fetch
//   - 'enology'  chunk_type=enology overview, QA fetch combines chunk_type=qa
//                 + chunk_type=enology (section_title != Overview) matches
//
// matchTerm (topic page's own QA content filter) defaults to topicName if
// omitted. excludeTerm is rare (only cabernet-sauvignon needs it, to keep
// "Cabernet Franc" mentions out of the Cabernet Sauvignon page).
//
// keywordPattern (regex source, no slashes, always case-insensitive) is what
// supabase-client.js uses to route an arbitrary answer card to this topic
// page when its source_doc doesn't already resolve one. Defaults to the
// escaped topicName when omitted — only set it when that default would be
// wrong (topicName has an extra word the content doesn't use, like "Niagara
// Peninsula", or needs to allow for a spelling/boundary variant).
//
// Array order matters here: it becomes TOPIC_KEYWORDS' match order, and
// multi-word patterns must come before single-word ones so e.g. "Chenin
// Blanc" matches before a shorter, coincidental single-word hit would.

export const BASE_URL = 'https://knowledge.thirstyc.com';

// Static (non-topic) pages included in sitemap.xml, as paths relative to
// the site root ('' = homepage). Deliberately excludes:
//   - search.html, 404.html: standard practice, not real content pages.
//   - audience-enthusiast.html: still a hand-built mockup with fabricated
//     placeholder answers and dead links to pages that don't exist --
//     indexing it would put fake content in search results. No audience
//     field exists anywhere in the schema to regenerate it from (see
//     PIPELINE-GAP-AUDIT.md); add it back once that's decided.
//   - answer-*.html (904 pages): generated by generate-missing-pages.mjs
//     from knowledge_chunks, not listed here individually. Not yet in the
//     sitemap -- would need that generator's output wired into this
//     (currently synchronous, DB-free) script to include automatically.
//   - difficulty-intermediate.html/difficulty-beginner.html WERE excluded
//     here as fabricated mockups; both are now generated from real
//     Beginner/Intermediate knowledge_chunks rows, so they're back in.
export const STATIC_PAGES = [
  '',
  'about.html',
  'answers.html',
  'topics.html',
  'grapes.html',
  'regions.html',
  'guides.html',
  'answer-grenache-alcohol-tannin.html',
  'difficulty-beginner.html',
  'difficulty-intermediate.html',
];

export const TOPICS = [
  {
    slug: 'chenin-blanc',
    kind: 'grape',
    topicName: 'Chenin Blanc',
    sourceDoc: 'grape-chenin-blanc',
    metaDescription: 'Bone-dry to lusciously sweet, one grape doing it all. Everything we know about Chenin Blanc.',
  },
  {
    slug: 'cabernet-sauvignon',
    kind: 'grape',
    topicName: 'Cabernet Sauvignon',
    sourceDoc: 'grape-cabernet-sauvignon',
    metaDescription: 'Structured, tannic, built to age. Everything we know about Cabernet Sauvignon.',
    matchTerm: 'Cabernet',
    excludeTerm: 'Franc',
    note:
      'Most entries just say "Cabernet", not the full varietal name, so we ' +
      'match broadly and exclude Cabernet Franc mentions instead of requiring ' +
      'the exact phrase (which was missing ~32 of the 40 real matches).',
  },
  {
    slug: 'rhone-valley',
    kind: 'region',
    topicName: 'Rhône Valley',
    sourceDoc: 'region-rhone',
    metaDescription: 'Syrah in the north, Gren­ache blends in the south. Everything we know about the Rhône Valley.',
    matchTerm: 'Rhône',
    keywordPattern: 'rh[oô]ne',
  },
  {
    slug: 'nebbiolo',
    kind: 'grape',
    topicName: 'Nebbiolo',
    sourceDoc: 'grape-nebbiolo',
    metaDescription: 'Pale in color, ferociously tannic. Everything we know about Nebbiolo.',
  },
  {
    slug: 'gamay',
    kind: 'grape',
    topicName: 'Gamay',
    sourceDoc: 'grape-gamay',
    metaDescription: 'Light, juicy, chillable red from Beaujolais. Everything we know about Gamay.',
    keywordPattern: '\\bgamay\\b',
  },
  {
    slug: 'riesling',
    kind: 'grape',
    topicName: 'Riesling',
    sourceDoc: 'grape-riesling',
    metaDescription: 'Aromatic and misunderstood. Everything we know about Riesling.',
  },
  {
    slug: 'burgundy',
    kind: 'region',
    topicName: 'Burgundy',
    sourceDoc: 'region-burgundy',
    metaDescription: "The world's most detailed expression of terroir. Everything we know about Burgundy.",
  },
  {
    slug: 'priorat',
    kind: 'region',
    topicName: 'Priorat',
    sourceDoc: 'region-priorat',
    metaDescription: 'Dark, mineral reds off steep Spanish slate. Everything we know about Priorat.',
  },
  {
    slug: 'jura',
    kind: 'region',
    topicName: 'Jura',
    sourceDoc: 'region-jura',
    metaDescription: "France's strangest, most beloved region. Everything we know about Jura.",
    keywordPattern: '\\bjura\\b',
  },
  {
    slug: 'etna',
    kind: 'region',
    topicName: 'Etna',
    sourceDoc: 'region-etna',
    metaDescription: "Volcanic wine from the slopes of Sicily's active volcano. Everything we know about Etna.",
    keywordPattern: '\\betna\\b',
  },
  {
    slug: 'niagara',
    kind: 'region',
    topicName: 'Niagara Peninsula',
    sourceDoc: 'region-niagara',
    metaDescription: "Canada's cool-climate Riesling and ice wine country. Everything we know about Niagara.",
    matchTerm: 'Niagara',
    keywordPattern: 'niagara',
  },
  {
    slug: 'grenache',
    kind: 'grape',
    topicName: 'Grenache',
    sourceDoc: 'grape-grenache',
    metaDescription: 'Soft, generous, high in alcohol and low in grip. Everything we know about Grenache.',
  },
  {
    slug: 'biodynamic',
    kind: 'enology',
    topicName: 'Biodynamic Wine',
    sourceDoc: 'enology-biodynamic',
    metaDescription: 'Farming by the lunar calendar. Everything we know about biodynamic wine.',
    matchTerm: 'Biodynamic',
    keywordPattern: 'biodynamic',
  },
  {
    slug: 'fermentation',
    kind: 'enology',
    topicName: 'Fermentation',
    sourceDoc: 'enology-fermentation',
    metaDescription: 'How grape juice becomes wine. Everything we know about fermentation.',
  },
  {
    slug: 'sulphites',
    kind: 'enology',
    topicName: 'Sulphites',
    sourceDoc: 'enology-sulphites',
    metaDescription: "The winemaker's essential preservative, and the headache myth around it. Everything we know about sulphites.",
    matchTerm: 'Sulfite',
    keywordPattern: 'sulf?ite',
  },
  {
    slug: 'tannins',
    kind: 'enology',
    topicName: 'Tannins',
    sourceDoc: 'enology-tannins',
    metaDescription: "Where grip comes from, and why it fades with age. Everything we know about tannins.",
    matchTerm: 'Tannin',
    keywordPattern: '\\btannins?\\b',
  },
  {
    slug: 'oak',
    kind: 'enology',
    topicName: 'Oak',
    sourceDoc: 'enology-oak',
    metaDescription: 'Vanilla, spice, and texture from the barrel. Everything we know about oak.',
    keywordPattern: '\\boak\\b',
  },
  {
    slug: 'faults',
    kind: 'enology',
    topicName: 'Wine Faults',
    sourceDoc: 'enology-faults',
    metaDescription: 'Flaw or style choice? Everything we know about wine faults.',
    matchTerm: 'Fault',
    keywordPattern: '\\bfault(s|y)?\\b',
  },
];
