// Single source of truth for topic-*.html pages AND for the answer-card
// routing table in supabase-client.js (TOPIC_PAGE_SLUGS, SOURCE_DOC_SLUG_
// OVERRIDES, TOPIC_KEYWORDS). Add an entry here and run
// `npm run generate:topics` instead of hand-editing either.
//
// kind determines which Supabase query shape generate-topic-pages.mjs uses:
//   - 'grape'    chunk_type=grape overview, single chunk_type=qa QA fetch
//   - 'region'   chunk_type=region overview, single chunk_type=region-qa QA fetch
//   - 'enology'  chunk_type=enology overview, QA fetch combines chunk_type=qa
//                 + chunk_type=enology (section_title != Overview) matches
//
// matchTerm (topic page's own QA content filter) defaults to topicName if
// omitted. excludeTerm is rare (only cabernet-sauvignon needs it, to keep
// "Cabernet Franc" mentions out of the Cabernet Sauvignon page).
//
// keywordPattern (regex source, no slashes, always case-insensitive) is what
// supabase-client.js uses to route an arbitrary answer card to this topic
// page when its source_doc doesn't already resolve one. Defaults to the
// escaped topicName when omitted — only set it when that default would be
// wrong (topicName has an extra word the content doesn't use, like "Niagara
// Peninsula", or needs to allow for a spelling/boundary variant).
//
// Array order matters here: it becomes TOPIC_KEYWORDS' match order, and
// multi-word patterns must come before single-word ones so e.g. "Chenin
// Blanc" matches before a shorter, coincidental single-word hit would.

export const BASE_URL = 'https://knowledge.thirstyc.com';

export function escapeRegex(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

// The regex generate-topic-pages.mjs's routing table (TOPIC_KEYWORDS) and
// generate-missing-pages.mjs's resolveTopicLink() both test against a
// chunk's content to find its topic page -- content can be English or
// French, so where translation changed the word entirely (not just a proper
// noun that survives untouched), keywordPatternFr covers the French phrasing
// and this unions the two into one pattern that matches either language.
// Most topics don't need it: grape/region proper nouns are usually unchanged
// in French, so keywordPattern alone already matches both languages.
export function effectiveKeywordPattern(topic) {
  const en = topic.keywordPattern ?? escapeRegex(topic.topicName.toLowerCase());
  return topic.keywordPatternFr ? `(?:${en})|(?:${topic.keywordPatternFr})` : en;
}

// Static (non-topic) pages included in sitemap.xml, as paths relative to
// the site root ('' = homepage). Deliberately excludes:
//   - search.html, 404.html: standard practice, not real content pages.
//   - audience-enthusiast.html: still a hand-built mockup with fabricated
//     placeholder answers and dead links to pages that don't exist --
//     indexing it would put fake content in search results. No audience
//     field exists anywhere in the schema to regenerate it from (see
//     PIPELINE-GAP-AUDIT.md); add it back once that's decided.
//   - answer-*.html: generated by generate-missing-pages.mjs from
//     knowledge_chunks, not listed here individually -- lib/sitemap.mjs
//     picks up every answer-*.html on disk automatically.
//   - difficulty-intermediate.html/difficulty-beginner.html WERE excluded
//     here as fabricated mockups; both are now generated from real
//     Beginner/Intermediate knowledge_chunks rows, so they're back in.
export const STATIC_PAGES = [
  '',
  'about.html',
  'answers.html',
  'grapes.html',
  'regions.html',
  'guides.html',
  'answer-grenache-alcohol-tannin.html',
  'difficulty-beginner.html',
  'difficulty-intermediate.html',
];

export const TOPICS = [
  {
    slug: 'chenin-blanc',
    kind: 'grape',
    topicName: 'Chenin Blanc',
    sourceDoc: 'grape-chenin-blanc',
    metaDescription: 'Bone-dry to lusciously sweet, one grape doing it all. Everything we know about Chenin Blanc.',
    // French sometimes pluralizes both words as a common noun ("des chenins
    // blancs"), which the default escaped-exact-phrase pattern doesn't
    // match -- found via a cross-topic answer-page audit (a region-qa row
    // mentioning the grape only in passing, not the grape's own topic page).
    keywordPatternFr: 'chenins? blancs?',
    frReady: true,
    metaDescriptionFr: 'Du plus sec au plus liquoreux, un seul cépage sait tout faire. Tout ce que nous savons sur le Chenin Blanc.',
  },
  {
    slug: 'cabernet-sauvignon',
    kind: 'grape',
    topicName: 'Cabernet Sauvignon',
    sourceDoc: 'grape-cabernet-sauvignon',
    metaDescription: 'Structured, tannic, built to age. Everything we know about Cabernet Sauvignon.',
    matchTerm: 'Cabernet',
    excludeTerm: 'Franc',
    note:
      'Most entries just say "Cabernet", not the full varietal name, so we ' +
      'match broadly and exclude Cabernet Franc mentions instead of requiring ' +
      'the exact phrase (which was missing ~32 of the 40 real matches).',
    frReady: true,
    metaDescriptionFr: 'Structuré, tannique, fait pour vieillir. Tout ce que nous savons sur le Cabernet Sauvignon.',
  },
  {
    slug: 'rhone-valley',
    kind: 'region',
    topicName: 'Rhône Valley',
    sourceDoc: 'region-rhone',
    metaDescription: 'Syrah in the north, Gren­ache blends in the south. Everything we know about the Rhône Valley.',
    matchTerm: 'Rhône',
    keywordPattern: 'rh[oô]ne',
    // "Rhône" itself is unchanged in French; only the full topic name
    // translates ("Vallée du Rhône"), so no matchTermFr/keywordPatternFr
    // is needed -- the existing pattern already matches French content.
    topicNameFr: 'Vallée du Rhône',
    frReady: true,
    metaDescriptionFr: "La Syrah au nord, des assemblages de Grenache au sud. Tout ce que nous savons sur la vallée du Rhône.",
  },
  {
    slug: 'nebbiolo',
    kind: 'grape',
    topicName: 'Nebbiolo',
    sourceDoc: 'grape-nebbiolo',
    metaDescription: 'Pale in color, ferociously tannic. Everything we know about Nebbiolo.',
    frReady: true,
    metaDescriptionFr: 'Pâle en couleur, redoutablement tannique. Tout ce que nous savons sur le Nebbiolo.',
  },
  {
    slug: 'gamay',
    kind: 'grape',
    topicName: 'Gamay',
    sourceDoc: 'grape-gamay',
    metaDescription: 'Light, juicy, chillable red from Beaujolais. Everything we know about Gamay.',
    // Beaujolais is Gamay, and answers often name the region, not the grape.
    keywordPattern: '\\bgamay\\b|\\bbeaujolais\\b',
    frReady: true,
    metaDescriptionFr: 'Rouge léger, juteux, à servir frais, venu du Beaujolais. Tout ce que nous savons sur le Gamay.',
  },
  {
    slug: 'riesling',
    kind: 'grape',
    topicName: 'Riesling',
    sourceDoc: 'grape-riesling',
    metaDescription: 'Aromatic and misunderstood. Everything we know about Riesling.',
    // topicNameFr is unset because "Riesling" is unchanged in French.
    frReady: true,
    metaDescriptionFr: 'Aromatique et incompris. Tout ce que nous savons sur le Riesling.',
  },
  {
    slug: 'burgundy',
    kind: 'region',
    topicName: 'Burgundy',
    sourceDoc: 'region-burgundy',
    metaDescription: "The world's most detailed expression of terroir. Everything we know about Burgundy.",
    // "Burgundy" is translated to the French exonym "Bourgogne", not kept
    // as-is -- matchTermFr/keywordPatternFr needed or French QA rows and
    // routing would never match the English word.
    matchTermFr: 'Bourgogne',
    keywordPatternFr: 'bourgogne',
    topicNameFr: 'Bourgogne',
    frReady: true,
    metaDescriptionFr: "L'expression la plus détaillée du terroir au monde. Tout ce que nous savons sur la Bourgogne.",
  },
  {
    slug: 'priorat',
    kind: 'region',
    topicName: 'Priorat',
    sourceDoc: 'region-priorat',
    metaDescription: 'Dark, mineral reds off steep Spanish slate. Everything we know about Priorat.',
    frReady: true,
    metaDescriptionFr: "Des rouges sombres et minéraux nés de l'ardoise espagnole abrupte. Tout ce que nous savons sur le Priorat.",
  },
  {
    slug: 'jura',
    kind: 'region',
    topicName: 'Jura',
    sourceDoc: 'region-jura',
    metaDescription: "France's strangest, most beloved region. Everything we know about Jura.",
    keywordPattern: '\\bjura\\b',
    frReady: true,
    metaDescriptionFr: 'La région la plus singulière et la plus attachante de France. Tout ce que nous savons sur le Jura.',
  },
  {
    slug: 'etna',
    kind: 'region',
    topicName: 'Etna',
    sourceDoc: 'region-etna',
    metaDescription: "Volcanic wine from the slopes of Sicily's active volcano. Everything we know about Etna.",
    keywordPattern: '\\betna\\b',
    frReady: true,
    metaDescriptionFr: "Un vin volcanique né des pentes du volcan actif de Sicile. Tout ce que nous savons sur l'Etna.",
  },
  {
    slug: 'niagara',
    kind: 'region',
    topicName: 'Niagara Peninsula',
    sourceDoc: 'region-niagara',
    metaDescription: "Canada's cool-climate Riesling and ice wine country. Everything we know about Niagara.",
    matchTerm: 'Niagara',
    keywordPattern: 'niagara',
    topicNameFr: 'Péninsule du Niagara',
    frReady: true,
    metaDescriptionFr: 'La région canadienne du Riesling et du vin de glace en climat frais. Tout ce que nous savons sur le Niagara.',
  },
  {
    slug: 'grenache',
    kind: 'grape',
    topicName: 'Grenache',
    sourceDoc: 'grape-grenache',
    metaDescription: 'Soft, generous, high in alcohol and low in grip. Everything we know about Grenache.',
    // Pilot for French localization (see scripts/translate-to-french.mjs):
    // the first topic with lang='fr' content translated.
    // topicNameFr is unset because "Grenache" is unchanged in French.
    frReady: true,
    metaDescriptionFr: 'Souple, généreux, riche en alcool et peu tannique. Tout ce que nous savons sur le Grenache.',
  },
  {
    slug: 'biodynamic',
    kind: 'enology',
    topicName: 'Biodynamic Wine',
    sourceDoc: 'enology-biodynamic',
    metaDescription: 'Farming by the lunar calendar. Everything we know about biodynamic wine.',
    matchTerm: 'Biodynamic',
    keywordPattern: 'biodynamic',
    // "Biodynamic" -> "biodynamique" -- not a substring match of the
    // English word (diverges at "biodynami{c vs que}"), needs its own term.
    matchTermFr: 'biodynamique',
    keywordPatternFr: 'biodynamique',
    topicNameFr: 'Vin biodynamique',
    frReady: true,
    metaDescriptionFr: 'Cultiver selon le calendrier lunaire. Tout ce que nous savons sur le vin biodynamique.',
  },
  {
    slug: 'fermentation',
    kind: 'enology',
    topicName: 'Fermentation',
    sourceDoc: 'enology-fermentation',
    metaDescription: 'How grape juice becomes wine. Everything we know about fermentation.',
    frReady: true,
    metaDescriptionFr: 'Comment le jus de raisin devient du vin. Tout ce que nous savons sur la fermentation.',
  },
  {
    slug: 'sulphites',
    kind: 'enology',
    topicName: 'Sulphites',
    sourceDoc: 'enology-sulphites',
    metaDescription: "The winemaker's essential preservative, and the headache myth around it. Everything we know about sulphites.",
    matchTerm: 'Sulfite',
    keywordPattern: 'sulf?ite',
    // "sulfite" is spelled identically in French -- existing pattern
    // already matches both languages, no *Fr fields needed.
    topicNameFr: 'Sulfites',
    frReady: true,
    metaDescriptionFr: "Le conservateur essentiel du vigneron, et le mythe du mal de tête qui l'entoure. Tout ce que nous savons sur les sulfites.",
  },
  {
    slug: 'tannins',
    kind: 'enology',
    topicName: 'Tannins',
    sourceDoc: 'enology-tannins',
    metaDescription: "Where grip comes from, and why it fades with age. Everything we know about tannins.",
    matchTerm: 'Tannin',
    keywordPattern: '\\btannins?\\b',
    // French uses the correct single-n spelling ("tanin"/"tanins", enforced
    // via the DeepL glossary -- see scripts/translate-to-french-deepl.mjs),
    // which the English double-n pattern doesn't match.
    matchTermFr: 'tanin',
    keywordPatternFr: '\\btanins?\\b',
    topicNameFr: 'Tanins',
    frReady: true,
    metaDescriptionFr: "D'où vient la structure tannique, et pourquoi elle s'adoucit avec l'âge. Tout ce que nous savons sur les tanins.",
  },
  {
    slug: 'oak',
    kind: 'enology',
    topicName: 'Oak',
    sourceDoc: 'enology-oak',
    metaDescription: 'Vanilla, spice, and texture from the barrel. Everything we know about oak.',
    keywordPattern: '\\boak\\b',
    // "Oak" -> "chêne" in French (also enforced via the DeepL glossary) --
    // an entirely different word, needs its own match/keyword pattern. Some
    // rows describe barrel ageing without naming the wood ("non boisé",
    // "élevé en fût"), so match those phrasings too or the topic page
    // undercounts rows that plainly are about oak.
    matchTermFr: ['chêne', 'boisé', 'fût'],
    keywordPatternFr: '\\bch[êe]ne\\b|\\bbois[ée]s?\\b|\\bf[uû]ts?\\b',
    topicNameFr: 'Chêne',
    frReady: true,
    metaDescriptionFr: 'Vanille, épices et texture venues du fût. Tout ce que nous savons sur le chêne.',
  },
  {
    slug: 'faults',
    kind: 'enology',
    topicName: 'Wine Faults',
    sourceDoc: 'enology-faults',
    metaDescription: 'Flaw or style choice? Everything we know about wine faults.',
    matchTerm: 'Fault',
    keywordPattern: '\\bfault(s|y)?\\b',
    // "Fault" -> "défaut" in French -- an entirely different word.
    matchTermFr: 'défaut',
    keywordPatternFr: 'd[ée]fauts?',
    topicNameFr: 'Défauts du vin',
    frReady: true,
    metaDescriptionFr: 'Défaut ou choix de style ? Tout ce que nous savons sur les défauts du vin.',
  },
  {
    slug: 'sparkling',
    kind: 'enology',
    topicName: 'Sparkling Wine',
    sourceDoc: 'enology-sparkling',
    metaDescription: 'How the bubbles get in, and what each method tastes like. Everything we know about sparkling wine.',
    matchTerm: 'sparkling',
    keywordPattern: '\\bsparkling\\b',
    // French uses several words for the category depending on pressure and
    // style ("mousseux", "effervescent", "pétillant"), none of them cognates.
    matchTermFr: ['mousseux', 'effervescent', 'pétillant'],
    keywordPatternFr: '\\bmousseux\\b|\\beffervescents?\\b|\\bp[ée]tillants?\\b',
    topicNameFr: 'Vins effervescents',
    frReady: true,
    metaDescriptionFr: "D'où viennent les bulles, et ce que chaque méthode donne dans le verre. Tout ce que nous savons sur les vins effervescents.",
  },
  {
    slug: 'fortified',
    kind: 'enology',
    topicName: 'Fortified Wine',
    sourceDoc: 'enology-fortified',
    metaDescription: 'Port, Sherry, Madeira and the rest: what adding spirit does. Everything we know about fortified wine.',
    matchTerm: 'fortified',
    keywordPattern: '\\bfortified\\b',
    // "muté" is the French technical term; "fortifié" is common in Quebec.
    matchTermFr: ['fortifié', 'muté'],
    keywordPatternFr: '\\bfortifi[ée]e?s?\\b|\\bmut[ée]e?s?\\b',
    topicNameFr: 'Vins fortifiés',
    frReady: true,
    metaDescriptionFr: "Porto, xérès, madère : ce que l'ajout d'eau-de-vie change. Tout ce que nous savons sur les vins fortifiés.",
  },
];
